### ISSUE TITLE
Latest Hass 0.113 Update Broke

### ISSUE THREAD

**Issue by heyepic** [JuanMTech/google_dark_theme#26]
See screenshots below of the before/after.
![Status](https://user-images.githubusercontent.com/12517908/88210808-5d9ce200-cc1a-11ea-94d5-58643dd39329.png)
![Status2](https://user-images.githubusercontent.com/12517908/88210830-62fa2c80-cc1a-11ea-890d-c22037b62b2a.png)

**Comment by heyepic** [comment]
Note from devs:

> The theme variable paper-card-background-color is removed. You can use ha-card-background or card-background-color as a replacement.
> 
> In general, all variables that start with paper will be removed at some point.

**Comment by heyepic** [comment]
Fixed with the following:

`# Theme based on Google app dark theme
# Creator: Juan - @juanmtech
# Website: https://www.juanmtech.com
# YouTube Channel: https://youtube.com/juanmtech
# My Home Assistant Config files: https://github.com/JuanMTech/Home_Assistant_files
#
#
Google Dark Theme:
  # Header:
  app-header-background-color: "#171717"
  app-header-text-color: "#BDC1C6"
  # Main Interface Colors
  primary-color: "#5F9BEA"
  light-primary-color: var(--primary-color)
  primary-background-color: "#171717"
  secondary-background-color: "#202124"
  divider-color: var(--primary-background-color)
  # Text
  primary-text-color: "#BDC1C6"
  secondary-text-color: "#BDC1C6"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#717171"
  # Sidebar Menu
  sidebar-icon-color: var(--app-header-text-color)
  sidebar-text-color: '#BDC1C6'
  sidebar-background-color: "#202124"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#5F9BEA"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color))
  # States and Badges
  state-icon-color: "#5F6267"
  state-icon-active-color: "#5F9BEA"
  state-icon-unavailable-color: var(--disabled-text-color)
  # Sliders
  ha-slider-knob-color: "#5F9BEA"
  ha-slider-knob-start-color: var(--ha-slider-knob-color)
  ha-slider-pin-color: var(--ha-slider-knob-color)
  ha-slider-active-color: var(--ha-slider-knob-color)
  ha-slider-secondary-color: var(--light-primary-color)
  # Labels
  label-badge-background-color: "#202124"
  label-badge-text-color: "#BDC1C6"
  label-badge-red: "#D06568"
  label-badge-green: "#80C884"
  label-badge-blue: "#5F9BEA"
  label-badge-yellow: "#DFC271"
  label-badge-gray: "#5F6267"

  # Cards
  ha-card-border-radius: "10px"
  ha-card-box-shadow: 1px 1px 5px 0px rgb(12, 12, 14)
  ha-dialog-background-color: "#202124"
  ha-card-background: var(--ha-dialog-background-color)
  ha-listbox-background-color: var(--ha-dialog-background-color)
  # Switches
  switch-checked-button-color: "#5F9BEA"
  switch-checked-track-color: "#404D64"
  switch-unchecked-button-color: "#636466"
  switch-unchecked-track-color: "#636466"
  # Toggles
  ha-toggle-button-checked-button-color: var(--switch-checked-button-color)
  ha-toggle-button-checked-bar-color: var(--switch-checked-track-color)
  ha-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
  ha-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)
  # Table
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
  data-table-background-color: var(--primary-background-color)
  # Dropdowns
  material-background-color: var(--secondary-background-color)
  material-secondary-background-color: var(--primary-background-color)
  mdc-theme-surface: var(--secondary-background-color)`

**Comment by davidrustingha** [comment]
Yep, I have it too. Tried to change it to the new name but that didn’t work sadly.

**Comment by tmpneves** [comment]
> Yep, I have it too. Tried to change it to the new name but that didn’t work sadly.

Same here!

**Comment by snakuzzo** [comment]
> > Yep, I have it too. Tried to change it to the new name but that didn’t work sadly.
> 
> Same here!

The Fix solved the problem.
You need to call service `frontend.reload_themes`

**Comment by tmpneves** [comment]
Still getting the same error, even after changing the name and calling the service. Any suggestions?

**Comment by snakuzzo** [comment]
Clear your browser cache

**Comment by JuanMTech** [comment]
It's now fixed with v1.7

**Comment by davidrustingha** [comment]
Its supposed to be fixed but I still see the cards in white. In the Android app and also on chrome. I deleted cache on both devices but it still shows.
